services:
  - type: web
    name: mock-interview-api
    runtime: python
    plan: free
    rootDir: mock-interview-platform/backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 100 --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_GEMINI_API_KEY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: False
